// <auto-generated />
using System;
using ColabRH.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColabRH.Data.Migrations
{
    [DbContext(typeof(ColabRHDbContext))]
    [Migration("20231019200302_Operadora_Produto_Plano")]
    partial class Operadora_Produto_Plano
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.GrauParentesco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoGrauParentesco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("GrausParentesco");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.GrupoEconomico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GruposEconomicos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Operadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Operadoras");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperadoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoAbrangencia")
                        .HasColumnType("int");

                    b.Property<int>("TipoAcomodacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperadoraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperadoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperadoraId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Sindicato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Sindicatos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Situacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoSituacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Vinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoMapeamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoEconomicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEconomicoId");

                    b.ToTable("Vinculos");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Cargo", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.Grade", "Grade")
                        .WithMany("Cargos")
                        .HasForeignKey("GradeId");

                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Departamento", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Empresa", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Grade", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.GrauParentesco", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Operadora", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Plano", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.Operadora", "Operadora")
                        .WithMany()
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColabRH.Business.Models.Cadastros.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operadora");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Produto", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.Operadora", "Operadora")
                        .WithMany()
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operadora");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Sindicato", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Situacao", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Vinculo", b =>
                {
                    b.HasOne("ColabRH.Business.Models.Cadastros.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("ColabRH.Business.Models.Cadastros.Grade", b =>
                {
                    b.Navigation("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
